In [62]:
import kagglehub
import shutil
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import adjustText as adjust_text
import os
from datetime import datetime

path = kagglehub.dataset_download("rohitgrewal/airlines-flights-data")

dest = "/Users/isaacguediri/Desktop/kaggle_files"
shutil.copytree(path, dest, dirs_exist_ok=True)

csv = pd.read_csv(dest+'/airlines_flights_data.csv')

#Questions to answer:
'''
Q.1. What are the airlines in the dataset, accompanied by their frequencies?

Q.2. Show Bar Graphs representing the Departure Time & Arrival Time.

Q.3. Show Bar Graphs representing the Source City & Destination City.

Q.4. Does price varies with airlines ?

Q.5. Does ticket price change based on the departure time and arrival time?

Q.6. How the price changes with change in Source and Destination?

Q.7. How is the price affected when tickets are bought in just 1 or 2 days before departure?

Q.8. How does the ticket price vary between Economy and Business class?

Q.9. What will be the Average Price of Vistara airline for a flight from Delhi to Hyderabad in Business Class ?
'''

#Dataset link: https://www.kaggle.com/datasets/rohitgrewal/airlines-flights-data

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.13)

'\nQ.1. What are the airlines in the dataset, accompanied by their frequencies?\n\nQ.2. Show Bar Graphs representing the Departure Time & Arrival Time.\n\nQ.3. Show Bar Graphs representing the Source City & Destination City.\n\nQ.4. Does price varies with airlines ?\n\nQ.5. Does ticket price change based on the departure time and arrival time?\n\nQ.6. How the price changes with change in Source and Destination?\n\nQ.7. How is the price affected when tickets are bought in just 1 or 2 days before departure?\n\nQ.8. How does the ticket price vary between Economy and Business class?\n\nQ.9. What will be the Average Price of Vistara airline for a flight from Delhi to Hyderabad in Business Class ?\n'

In [ ]:
#removing unnecessary column
csv.drop(columns='index', inplace=True)

In [ ]:
#changing duration format to more readble format
csv['duration'] = pd.to_timedelta(csv['duration'], unit='h')
func = lambda x: f'{int(x.total_seconds()//3600)}h {int((x.total_seconds()%3600)//60):02d}m'
csv['duration'] = csv['duration'].apply(func)

In [71]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   flight            300153 non-null  object
 2   source_city       300153 non-null  object
 3   departure_time    300153 non-null  object
 4   stops             300153 non-null  object
 5   arrival_time      300153 non-null  object
 6   destination_city  300153 non-null  object
 7   class             300153 non-null  object
 8   duration          300153 non-null  object
 9   days_left         300153 non-null  int64
 10  price             300153 non-null  int64
dtypes: int64(2), object(9)
memory usage: 25.2+ MB

In [72]:
csv.sample(5)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
81082,Vistara,UK-825,Mumbai,Morning,zero,Morning,Chennai,Economy,2h 04m,29,3020
295861,Vistara,UK-838,Chennai,Night,one,Night,Bangalore,Business,25h 34m,48,60260
234125,Air_India,AI-888,Mumbai,Evening,one,Evening,Bangalore,Business,21h 15m,49,54608
60045,Air_India,AI-867,Mumbai,Night,one,Afternoon,Bangalore,Economy,15h 00m,41,6502
12596,Air_India,AI-678,Delhi,Morning,one,Evening,Bangalore,Economy,9h 30m,15,4230

In [81]:
csv['stops'].unique()

array(['zero', 'one', 'two_or_more'], dtype=object)

In [ ]:
csv['stops'].apply(lambda x: "0" if x=='zero' else ("1" if x =="one" else (">2" if x == 'two_or_more' else str (x))))

0           0
1           0
2           0
3           0
4           0
         ...
300148    one
300149    one
300150    one
300151    one
300152    one
Name: stops, Length: 300153, dtype: object

In [77]:
csv.sample(5)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
92608,GO_FIRST,G8-283,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8h 40m,43,3702
261001,Vistara,UK-808,Bangalore,Early_Morning,one,Night,Chennai,Business,12h 15m,44,60396
164856,Air_India,AI-525,Hyderabad,Early_Morning,one,Night,Mumbai,Economy,14h 04m,44,4537
145494,Air_India,AI-402,Kolkata,Morning,one,Morning,Hyderabad,Economy,25h 30m,28,5145
110232,Indigo,6E-541,Bangalore,Morning,one,Evening,Hyderabad,Economy,7h 45m,7,5488